"""Only current context snapshot; NEVER sum snapshots as consumed tokens."""
import json
import sys
import os
from uuid import UUID
from pathlib import Path
from tokenlens.contract import new_event, number, model, finish_usage
from tokenlens.store import Store

def normalize(payload):
    e = new_event("claude_code", "claude_statusline", "context_snapshot")
    context = payload.get("context_window", {})
    e["execution"]["model"] = model(payload.get("model", {}).get("id"))
    e["usage"]["input_tokens"] = number(context.get("total_input_tokens"))
    e["usage"]["output_tokens"] = number(context.get("total_output_tokens"))
    return finish_usage(e)

def main():
    try:
        raw = sys.stdin.buffer.read(65537)
        if len(raw) > 65536:
            raise ValueError()
        event = normalize(json.loads(raw))
        # Random ID generated by our launcher, NEVER the provider's session ID.
        event["event_id"] = str(UUID(os.environ["TOKENLENS_OBSERVATION_ID"]))
        Store(Path(__file__).resolve().parents[1]/".local"/"telemetry.sqlite3").snapshot(event)
        print("TokenLens | contexto local registrado")
    except Exception:
        print("TokenLens | métrica indisponível")

if __name__ == "__main__":
    main()
