const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<label for="provider">Provedor</label><select id="provider"><option value="">Todos</option><option value="codex">Codex</option><option value="claude">Claude Code</option></select><button id="outside">Fora</button>',{runScripts:'outside-only'});
const w=dom.window,d=w.document;w.HTMLElement.prototype.scrollIntoView=function(){};
w.eval(fs.readFileSync('lab/static/dropdown.js','utf8'));
const button=d.querySelector('[role=combobox]'),select=d.querySelector('select');
const key=value=>button.dispatchEvent(new w.KeyboardEvent('keydown',{key:value,bubbles:true,cancelable:true}));
const options=()=>[...d.querySelectorAll('[role=option]')];
assert.equal(select.hidden,true);assert.equal(button.getAttribute('aria-label'),'Provedor');
button.click();assert.equal(button.getAttribute('aria-expanded'),'true');assert.equal(options().length,3);
options()[1].click();assert.equal(select.value,'codex');assert.equal(button.getAttribute('aria-expanded'),'false');
key(' ');key('ArrowDown');key('Enter');assert.equal(select.value,'claude');
key('Home');key('Escape');assert.equal(select.value,'claude');assert.equal(button.getAttribute('aria-expanded'),'false');
key(' ');key('Home');key('Enter');assert.equal(select.value,'');
key(' ');key('End');key('Enter');assert.equal(select.value,'claude');
button.click();d.dispatchEvent(new w.Event('scroll'));assert.equal(button.getAttribute('aria-expanded'),'true');
d.querySelector('#outside').dispatchEvent(new w.Event('pointerdown',{bubbles:true}));assert.equal(button.getAttribute('aria-expanded'),'false');
button.click();key('Tab');assert.equal(button.getAttribute('aria-expanded'),'false');
select.disabled=true;w.TokenLensDropdowns.upgrade();button.click();assert.equal(button.getAttribute('aria-expanded'),'false');assert.equal(button.tabIndex,-1);
dom.window.close();console.log('Custom dropdown: click, selection, keyboard, Escape, Tab, outside click, scroll and disabled state passed.');
